FORMAT: 1A
HOST: https://komornik.apiblueprint.org/

# Komornik app 

It's Komornik API app to manage your bills.



## Users collection

### login [POST] [/login]

+ Request (application/json)

        {
            "user": {
                "login": "wojcis",
                "password": "wojpass"
            }
        }
        
+ Response 200 (application/json)

        {
            "user": {
                "id": 1,
                "firstname": "wojciech",
                "lastname": "cisek",
                "login": "wojcis",
                "password_digest": "$2a$12$RcutM.ykDjynWWwcwjULB.oQRVBMbTtOvpxwQwRmPtgIZ6Lf45ys2",
                "mail": "woj@gmail.com",
                "created_at": "2023-01-08T11:55:34.183Z",
                "updated_at": "2023-01-08T11:55:34.183Z"
            },
            "token": "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxfQ.5ZCNzmcTcHefeEH0FVse8ebHQABcxiu53E6Y5HHGSAM"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Not found"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### getUsers [GET] [/users]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "firstname": "wojciech",
                "lastname": "cisek",
                "login": "wojcis",
                "password_digest": "$2a$12$RcutM.ykDjynWWwcwjULB.oQRVBMbTtOvpxwQwRmPtgIZ6Lf45ys2",
                "mail": "woj@gmail.com",
                "created_at": "2023-01-08T11:55:34.183Z",
                "updated_at": "2023-01-08T11:55:34.183Z"
            },
            {
                "id": 3,
                "firstname": "krzysiek",
                "lastname": "nowak",
                "login": "krzynow",
                "password_digest": "$2a$12$wxfAMDsmnrq7Je6p/VG3duyjQQ/qmk/0MbSIaLgK733YOTNuveBBa",
                "mail": "krzy@gmail.com",
                "created_at": "2023-01-08T12:54:53.000Z",
                "updated_at": "2023-01-08T12:54:53.000Z"
            }
        ]
        
+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Not found"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### getUser [GET] [/users/:id]

+ Response 200 (application/json)

        {   
            "mail": "marcikn@xd.pl"
            "firstname": "Marcin",
            "lastname": "Kolski",
            "login": "mkolski",
        }
        
+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Not found"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### createNewUser [POST] [/users]
+ Request (application/json)

        {
            "user": {
                "firstname": "testname",
                "lastname": "testlast",
                "login": "domiNEW_testhgj",
                "password": "qwertyqwerty",
                "mail": "dsgs@ryt.com"
            }
        }
+ Response 201 (application/json)

        {
            "user": {
                "id": 5,
                "firstname": "testname",
                "lastname": "testlast",
                "login": "domiNEW_testhgj",
                "password_digest": "$2a$12$AVBofYQznfxoCFgrz3Yaie3TXXYiskveSD7uTbhweNU3puFE7mlXW",
                "mail": "dsgs@ryt.com",
                "created_at": "2023-01-23T19:14:35.719Z",
                "updated_at": "2023-01-23T19:14:35.719Z"
            },
            "token": "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1fQ.dLDawzSs7jcWH-RM0agCVLnPRqCS7o8ZppzaCrzr9fE"
        }
  
+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Not found"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }
### deleteUser [DELETE] [/users/:id]
+ Request (application/json)

        {
            "id": 21
        }
+ Response 200 (application/json)

        {
            "message": "User deleted!"
        }
        
+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Not found"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### updateUser [PATCH] [/users/:id]

+ Request (application/json)

        {
          "id": 3,
          "firstname": "Emlynn",
          "lastname": "Eastabrook",
          "login": "Aurea",
          "password": "eb6WkMrjclPw",
          "mail": "aeastabrook0@walmart.com"
        }
        
+ Response 200 (application/json)

        {
          "id": 3,
          "firstname": "Emlynn",
          "lastname": "Eastabrook",
          "login": "Aurea",
          "password": "eb6WkMrjclPw",
          "mail": "aeastabrook0@walmart.com"
        }
        
+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Not found"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }


## Bills collection
 
### billCollection [GET] [/bills]

+ Response 200 (application/json)

        {
            "id": 1,
            "amount": 90,
            "created_at": "2023-01-23T19:52:55.356Z",
            "updated_at": "2023-01-23T19:52:55.356Z",
            "ispaid": false,
            "user_id": 1,
            "commitment_id": 4
        }
        
+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Not found"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }
 
### bill [GET] [/bills/:id]

+ Response 200 (application/json)

        {
            "id": 1,
            "amount": 90,
            "created_at": "2023-01-23T19:52:55.356Z",
            "updated_at": "2023-01-23T19:52:55.356Z",
            "ispaid": false,
            "user_id": 1,
            "commitment_id": 4
        }
        
+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Not found"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### PayTheBill [PATCH] [/bills/:id]

+ Request (application/json)

        {
            "ispaid": true
        }
        
+ Response 200 (application/json)

        {
            "ispaid": true,
            "id": 1,
            "amount": 90,
            "created_at": "2023-01-23T19:52:55.356Z",
            "updated_at": "2023-01-23T20:12:42.372Z",
            "user_id": 1,
            "commitment_id": 4
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Not found"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

## Commitments collection

### commitmentCollection [GET] [/commitments]

+ Response 200 (application/json)

        {
            "id": 2,
            "commitmentdesc": "Zakup środków czystości 12",
            "commitmentamount": 155,
            "occurancedate": "2023-11-02",
            "expirationdate": "2024-12-02",
            "created_at": "2023-01-07T16:04:04.347Z",
            "updated_at": "2023-01-07T16:04:04.347Z",
            "groupinfo_id": 1,
            "user_id": 2
        },
        {
            "id": 5,
            "commitmentdesc": "Zakup środków czystości 1234",
            "commitmentamount": 15,
            "occurancedate": "2023-11-02",
            "expirationdate": "2024-12-02",
            "created_at": "2023-01-07T17:30:47.761Z",
            "updated_at": "2023-01-07T17:30:47.761Z",
            "groupinfo_id": 1,
            "user_id": 2
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Not found"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### commitment [GET] [/commitments/:id]

+ Response 200 (application/json)

        {
            "id": 2,
            "commitmentdesc": "Zakup środków czystości 12",
            "commitmentamount": 155,
            "occurancedate": "2023-11-02",
            "expirationdate": "2024-12-02",
            "created_at": "2023-01-07T16:04:04.347Z",
            "updated_at": "2023-01-07T16:04:04.347Z",
            "groupinfo_id": 1,
            "user_id": 2
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Not found"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }


### createNewCommitment [POST] [/commitments]

+ Request (application/json)

        {
            "group_id": 3,
            "giver_id": 1,
            "commitmentdesc": "Zakup środków czystości asd3sdd",
            "commitmentamount": 5505,
            "occurancedate": "02.11.2023",
            "expirationdate": "02.12.2024"
        }

+ Response 201 (application/json)

        {
            "id": 17,
            "commitmentdesc": "Zakup środków czystości asd3sdd",
            "commitmentamount": 5505,
            "occurancedate": "2023-11-02",
            "expirationdate": "2024-12-02",
            "created_at": "2023-01-23T19:58:58.453Z",
            "updated_at": "2023-01-23T19:58:58.453Z",
            "groupinfo_id": 1,
            "user_id": 3
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Not found"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### deleteCommitment [DELETE] [/commitments/:id]

+ Request (application/json)

        {
            "commitmentID": 21
        }

+ Response 200 (application/json)

        {
            "Message": "Commitment deleted!"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Not found"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }


### commitmentUpdate [PATCH] [/groupinfos/:id/commitments/:id]

+ Request (application/json)

        {
            "group_id": 1,
            "user_id": 1,
            "commitmentdesc": "Zakup środków czystości asd3d",
            "commitmentamount": 105,
            "occurancedate": "02.11.2023",
            "expirationdate": "02.12.2024"
        }

+ Response 200 (application/json)

        {
            "message": "Zaaktualizowano! Jeśli wartość zobowiązania uległa zmianie - Nie zapomnij o ponownym podziale zobowiązania na rachunki!"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Not found"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }
        
### splitCommitment [POST] [/commitments/split]

+ Request (application/json)

        {
            "group_id": 1,
            "commitment_id": 1,
            "bills":    [
            { "user_id": 1, "amount": 100 },
            { "user_id": 2, "amount": 15 }
                        ]
        }

+ Response 201 (application/json)

[
        {
            "id": 30,
            "amount": 5000,
            "created_at": "2023-01-23T20:42:21.473Z",
            "updated_at": "2023-01-23T20:42:21.473Z",
            "ispaid": false,
            "user_id": 4,
            "commitment_id": 18
        },
        {
            "id": 31,
            "amount": 505,
            "created_at": "2023-01-23T20:42:21.492Z",
            "updated_at": "2023-01-23T20:42:21.492Z",
            "ispaid": false,
            "user_id": 2,
            "commitment_id": 18
        }
]

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Not found"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

        
## Groups collection
### groupCollection [GET] [/groupinfos]

+ Response 200 (application/json)

        {
            "id": 1,
            "groupname": "testowa6116",
            "created_at": "2023-01-07T16:02:36.962Z",
            "updated_at": "2023-01-07T17:45:37.434Z"
        },
        {
            "id": 4,
            "groupname": "testowa12",
            "created_at": "2023-01-07T17:30:57.599Z",
            "updated_at": "2023-01-07T17:30:57.599Z"
        },
        {
            "id": 5,
            "groupname": "testowa2221",
            "created_at": "2023-01-10T11:31:56.257Z",
            "updated_at": "2023-01-10T11:31:56.257Z"
        },
        {
            "id": 6,
            "groupname": "testowa1",
            "created_at": "2023-01-10T12:29:28.794Z",
            "updated_at": "2023-01-10T12:29:28.794Z"
        }
+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Content not found!"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### groupInfo [GET] [/groupinfos/:id]

+ Response 200 (application/json)

        {
        "id": 1,
        "groupname": "testowa6116",
        "created_at": "2023-01-07T16:02:36.962Z",
        "updated_at": "2023-01-07T17:45:37.434Z"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Content not found!"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### createNewGroup [POST] [/groupinfos]
+ Request (application/json)

        {
            "groupname": "testowa1"
        }

+ Response 201 (application/json)

        {
            "id": 7,
            "groupname": "testowa1",
            "created_at": "2023-01-23T19:24:11.410Z",
            "updated_at": "2023-01-23T19:24:11.410Z"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Not Found"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }
### addUserToGroup [POST] [/groupinfos/:id/users]
+ Request (application/json)

        {
            "user_id": 3
        }

+ Response 201 (application/json)

        {
            "Message": "Przypisano użytkownika do grupy"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Not Found"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### deleteGroup [DELETE] [/groupinfos/:id]
+ Request (application/json)

        {
            "group_id": 5
        }

+ Response 200 (application/json)

        {
            "Message": "Group deleted!"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Not Found"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }
### deleteUserFromGroup [DELETE] [/groupinfos/:id/users]
+ Request (application/json)

        {
            "user_id": 3
        }

+ Response 200 (application/json)

        {
            "Message": "Usunięto użytkownika z grupy"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Not Found"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### updateGroup [PATCH] [/groupinfos/:id]
+ Request (application/json)

        {
            "groupname": "testowa66"
        }

+ Response 200 (application/json)

        {
            "groupname": "testowa656",
            "id": 6,
            "created_at": "2023-01-10T12:29:28.794Z",
            "updated_at": "2023-01-23T19:36:09.002Z"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Not Found"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }