FORMAT: 1A
HOST: https://komornik.apiblueprint.org/

# Komornik app 

It's Komornik API app to manage your bills.



## Users collection

### userCollection [GET]

+ Response 200 (application/json)

        {   
            "userID": 11,
            "mail": "marcikn@xd.pl"
            "firstname": "Marcin",
            "lastname": "Kolski",
            "login": "mkolski",
        }
        
+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Content not found!"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### user [GET]

+ Response 200 (application/json)

        {   
            "mail": "marcikn@xd.pl"
            "firstname": "Marcin",
            "lastname": "Kolski",
            "login": "mkolski",
        }
        
+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Content not found!"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### createNewUser [POST]
+ Request (application/json)

        {
            "mail": "newmail@xd.pl" 
            "firstname": "Marcin",
            "lastname": "Kolski",
            "login": "mkolski",
            "password": "Ara$*kadabra2"
        }
+ Response 201 (application/json)

        {
            "mail": "newmail@xd.pl" 
            "userID": 11,
            "firstname": "Marcin",
            "lastname": "Kolski",
            "login": "mkolski",
            "password": "Ara$*kadabra2"
        }
  
+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Content not found!"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }
### deleteUser [DELETE]
+ Request (application/json)

        {
            "userID": 21
        }
+ Response 200 (application/json)

        {
            "Message": "Success!"
        }
        
+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Content not found!"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### updateUser [PATCH]

+ Request (application/json)

        {
            "mail": "newmail2@xd.pl" 
            "firstname": "Marcin",
            "lastname": "Kolski",
            "login": "mkolski",
            "password": "abrakadabra2"
        }
        
+ Response 200 (application/json)

        {
            "userID": 14,
            "mail": "newmail2@xd.pl" 
            "firstname": "Marcin",
            "lastname": "Kolski",
            "login": "mkolski",
            "password": "abrakadabra2"
        }
        
+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Content not found!"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }


## Bills collection
 
### billCollection [GET]

+ Response 200 (application/json)

        {
            "billID": 1,
            "recipientID": 1,
            "commitmentID": 1,
            "amount": 2.37,
            "isPaid": "no"
        }
        
+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Content not found!"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }
 
### bill [GET]

+ Response 200 (application/json)

        {
            "recipientID": 1,
            "commitmentID": 1,
            "amount": 2.37,
            "isPaid": "no"
        }
        
+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Content not found!"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### createNewBill [POST]
+ Request (application/json)

        {
            "recipientID": 11,
            "commitmentID": 113,
            "amount": 21.37,
            "isPaid": "no"
        }
        
+ Response 201 (application/json)

        {
            "billID": 11,
            "recipientID": 11,
            "commitmentID": 113,
            "amount": 21.37,
            "isPaid": "no"
        }
        
+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Content not found!"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }


### deleteBill [DELETE]
+ Request (application/json)

        {
            "billID": 21
        }

+ Response 200 (application/json)

        {
            "Message": "Success!"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Content not found!"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### billUpdate [PATCH]

+ Request (application/json)

        {
            "recipientID": 1,
            "commitmentID": 1,
            "amount": 25.37,
            "isPaid": "yes"
        }
        
+ Response 200 (application/json)

        {
            "billID": 1,
            "recipientID": 1,
            "commitmentID": 1,
            "amount": 25.37,
            "isPaid": "yes"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Content not found!"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

## Commitments collection

### commitmentCollection [GET]

+ Response 200 (application/json)

        {
            "commitmentID": 1,
            "commitmentDesc": "tekst",
            "commitmentAmount": 555,
            "occurenceDate": "12.12.2023",
            "expirationDate": "12.12.2054",
            "giverID": 1,
            "groupID": 1
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Content not found!"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### commitment [GET]

+ Response 200 (application/json)

        {
            "commitmentDesc": "tekst",
            "commitmentAmount": 555,
            "occurenceDate": "12.12.2023",
            "expirationDate": "12.12.2054",
            "giverID": 1,
            "groupID": 1
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Content not found!"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }


### createNewCommitment [POST]

+ Request (application/json)

        {
            "commitmentDesc": "tekst",
            "commitmentAmount": 555,
            "occurenceDate": "12.12.2023",
            "expirationDate": "12.12.2054",
            "giverID": 1,
            "groupID": 1
        }

+ Response 201 (application/json)

        {
            "commitmentID": 1,
            "commitmentDesc": "tekst",
            "commitmentAmount": 555,
            "occurenceDate": "12.12.2023",
            "expirationDate": "12.12.2054",
            "giverID": 1,
            "groupID": 1
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Content not found!"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### deleteCommitment [DELETE]

+ Request (application/json)

        {
            "commitmentID": 21
        }

+ Response 200 (application/json)

        {
            "Message": "Success!"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Content not found!"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }


### commitmentUpdate [PATCH]

+ Request (application/json)

        {
            "commitmentDesc": "tekst",
            "commitmentAmount": 555,
            "occurenceDate": "12.12.2023",
            "expirationDate": "12.12.2054",
            "giverID": 1,
            "groupID": 1
        }


+ Response 200 (application/json)

        {
            "commitmentID": 1,
            "commitmentDesc": "tekst",
            "commitmentAmount": 555,
            "occurenceDate": "12.12.2023",
            "expirationDate": "12.12.2054",
            "giverID": 1,
            "groupID": 1
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Content not found!"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }
        
## Groups collection
### groupCollection [GET]

+ Response 200 (application/json)

        {
            "groupID": 23,
            "groupName": "something1"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Content not found!"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### groupInfo [GET]

+ Response 200 (application/json)

        {
            "groupName": "something1"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Content not found!"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### createNewGroup [POST]
+ Request (application/json)

        {
            "groupName": "JLB"
        }

+ Response 201 (application/json)

        {
             "groupID": 10,
             "groupName": "JLB"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Content not found!"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }

### deleteGroup [DELETE]
+ Request (application/json)

        {
            "groupID": 66
        }

+ Response 200 (application/json)

        {
            "Message": "Success!"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Content not found!"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }


### updateGroup [PATCH]
+ Request (application/json)

        {
            "groupName": "test6"
        }

+ Response 200 (application/json)

        {
            "groupID": 10,
            "groupName": "test6"
        }

+ Response 400 (application/json)

        {
            "Message": "Bad Request"
        }

+ Response 404 (application/json)

        {
            "Message": "Content not found!"
        }

+ Response 503 (application/json)

        {
            "Message": "Service Unavailable"
        }